### PR TITLE
Introduce poetry(2nix), GitHub Actions, blackify all the files

### PR DESCRIPTION
**Pull request by andir**
Initially I wanted to hack on proper IPv6 support for NixOps on Hetzner. @grahamc convinced me to look into poetry and poetry2nix for this project. I fell for that trap.

Things done:

- [x] use poetry for dependency managemetn
- [x] introduce poetry2nix for packaging with Nix
- [x] ensure tests are still running (all 0 tests that I found with nose tests still work…)
- [x] add some simple CI to catch obvious Nix packaging, formatting & test errors (hah!)
- [x] updates development instructions

Future work:

- [ ] remove the overlay.nix once poetry2nix is up2date in the nixpkgs-unstable channel
- [ ] add type annotations and verify the using mypy (in CI)
- [ ] add some integration tests with hetzner credentials (cc @grahamc)
- [ ] do the actual tasks I wanted to do :D

### CODE REVIEW

**Comment by andir** [comment]
For the CI results you can have a look at my fork: https://github.com/andir/nixops-hetzner/actions/runs/67772822

**Comment by RoGryza** [comment]
What's the status on this PR? Is it waiting for a NixOps release with the new plugin format?
I want to hack on the Hetzner plugin but I'm using NixOps on the master branch

**Comment by andir** [comment]
On 06:17 23.09.20, Rodrigo Candido Gryzinski wrote:
> What's the status on this PR? Is it waiting for a NixOps release with the new plugin format?
> I want to hack on the Hetzner plugin but I'm using NixOps on the master branch

I only hacked this as initial draft to see how feasible a plugin
conversion is. I am not sure if we have a maintainer for this at all
that would even merge this without personally requiring this...

If you want to continue this please feel free to create another PR based
on this or lobby for getting it merged :)

**Comment by RoGryza** [comment]
@andir I ended up starting a separate plugin for Hetzner Cloud integration [https://github.com/RoGryza/nixops_hetznercloud](here) using the new NixOps plugin API, to be honest I'm not that inclined to put in the work on this conversion since I don't use Hetzner Robot

**Comment by tewfik-ghariani** [comment]
This PR is superseded by https://github.com/NixOS/nixops-hetzner/pull/45

**Pull request closed without merging**
